/** @type {import('tailwindcss').Config} */
module.exports = {
  // NOTE: Update this to include the paths to all files that contain Nativewind classes.
  content: ["./App.tsx", "./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      fontFamily: {
        black: ["Poppins-Black"],
        blackItalic: ["Poppins-BlackItalic"],
        bold: ["Poppins-Bold"],
        boldItalic: ["Poppins-BoldItalic"],
        extraBold: ["Poppins-ExtraBold"],
        extraBoldItalic: ["Poppins-ExtraBoldItalic"],
        extraLight: ["Poppins-ExtraLight"],
        extraLightItalic: ["Poppins-ExtraLightItalic"],
        italic: ["Poppins-Italic"],
        light: ["Poppins-Light"],
        lightItalic: ["Poppins-LightItalic"],
        medium: ["Poppins-Medium"],
        mediumItalic: ["Poppins-MediumItalic"],
        regular: ["Poppins-Regular"],
        semibold: ["Poppins-Semibold"],
        semiboldItalic: ["Poppins-SemiboldItalic"],
        thin: ["Poppins-Thin"],
        thinItalic: ["Poppins-ThinItalic"],
      },
      colors: {
        "violet-1": "#130D21",
        "violet-2": "#1A132C",
        "violet-3": "#2C1652",
        "violet-4": "#3A1470",
        "violet-5": "#441C7F",
        "violet-6": "#4F288E",
        "violet-7": "#5F35A6",
        "violet-8": "#7541CD",
        "violet-9": "#7E45DC",
        "violet-10": "#6F3AC6",
        "violet-11": "#BFA1FF",
        "violet-12": "#E5D9FF",
        "gris-1": "#111113",
        "gris-2": "#19191B",
        "gris-3": "#222325",
        "gris-4": "#292A2E",
        "gris-5": "#303136",
        "gris-6": "#393A40",
        "gris-7": "#46484F",
        "gris-8": "#5F606A",
        "gris-9": "#6C6E79",
        "gris-10": "#797B86",
        "gris-11": "#B2B3BD",
        "gris-12": "#EEEEF0",
        "vert": "#00E074",
        "jaune": "#FFDC10",
        "rouge": "#FF1474",
      }
    },
  },
  plugins: [],
}